name: My First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate build step
        run: echo "Building the project"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate test step
        run: echo "Running tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulate deploy step
        run: echo "Deploying the project"
